title: Matalan tason ohjelmointi
subtitle: Beta
lang: fi
baseurl: "/fi"
url: "https://hy-low.github.io"
theme-color: '#62c535'

plugins:
  - jekyll-remote-theme

remote_theme: ollpu/jekyll-course-theme@v2

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  # Uncomment for Finnish quotes:
  smart_quotes: rsquo,rsquo,rdquo,rdquo

permalink: /:title/

hide_other_section_menus: true

small_code_font: true

# If you want a collection of pages for course material:
collections:
  # In Finnish you might want to write e.g. "materiaali:" instead.
  material_1:
    output: true
    permalink: /:title/
  material_2:
    output: true
    permalink: /:title/

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
